version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    groups:
      terraform-plugin:
        patterns:
          - "github.com/hashicorp/terraform-plugin-*"
      indirect:
        dependency-type: indirect
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
