name: tagpr and release
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      tag:
        description: "release tag"
        required: false
        type: string

permissions:
  pull-requests: write
  contents: write
  actions: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          ref: ${{ inputs.tag || github.ref }}
      - uses: Songmu/tagpr@2afc990a4a5a9a340665cc1a484c2102f7de332f # v1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'workflow_dispatch' }}
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version: "1.27"
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}
      - name: Import GPG key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> 2"
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: 09AB4617FAC25EA0BAF1DF60EB1BEC09042C9789
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}
